### ISSUE TITLE
How to let nginx log the ssl key log file by changing nginx.conf file 

### ISSUE THREAD

**Issue by devkdas** [Water-Melon/ngx_http_autoquic_module#1]
Hi @Water-Melon   ,

My goal is capture the pcap file on my linux machine which is using nginx quic to connect and decrypt those packets using ssl key log file.but i am unable to find how to capture ssl key log file on nginx. Could someone please help me how to capture ssl key log file ?

Looking forward for you reply.

Thanks,
Kartheek.

**Comment by Water-Melon** [comment]
Sorry for replying you such late, and it is unfortunate I don't know it either.
Here is the answer that chatgpt gives:


Nginx does not natively support the generation of SSL key log files. However, you can use a workaround by using the openssl library to generate the SSL key log file. Here's how you can do it:

1. Recompile OpenSSL with debugging enabled

First, you need to recompile OpenSSL with the `sslkeylogfile` feature enabled. You can do this by setting the `SSLKEYLOGFILE` environment variable when compiling OpenSSL.

2. Recompile Nginx with the debug-enabled OpenSSL

After recompiling OpenSSL, you need to recompile Nginx with the newly compiled OpenSSL.

Here's an example of how you can do this:
```bash
# Download and extract the OpenSSL source code
wget https://www.openssl.org/source/openssl-1.1.1k.tar.gz
tar xzvf openssl-1.1.1k.tar.gz

# Compile OpenSSL with debugging enabled
cd openssl-1.1.1k
./config enable-ssl-trace enable-tls1_3 --prefix=/usr/local/ssl
make
sudo make install

# Download and extract the Nginx source code
wget http://nginx.org/download/nginx-1.19.10.tar.gz
tar xzvf nginx-1.19.10.tar.gz

# Compile Nginx with the debug-enabled OpenSSL
cd nginx-1.19.10
./configure --with-http_ssl_module --with-openssl=../openssl-1.1.1k
make
sudo make install
```
3. Set the SSLKEYLOGFILE environment variable

After recompiling Nginx, you can set the `SSLKEYLOGFILE` environment variable to the path where you want to save the SSL key log file.
```bash
export SSLKEYLOGFILE=/path/to/your/sslkeylogfile
```
4. Restart Nginx

Finally, restart Nginx to apply the changes.
```bash
sudo service nginx restart
```
Now, Nginx should generate an SSL key log file at the specified path when handling SSL/TLS connections.

Please note that this method is not recommended for production environments due to the potential security risks associated with logging SSL keys.
